# ===========================================================
#      Protein-glycan docking with HADDOCK3
#
#  This workflow will dock an unbound glycan (generated 
#  with GLYCAM) to an unbound protein, with van der 
#  Waals energy weight increased from 0.01 to 1.0 in 
#  the rigid body haddock scoring function and tip-ap 
#  restraints (true-interface-protein, glycan fully passive).
# ===========================================================

#general section

mode = "mpi"
ncores = 16
run_dir = "run_unbound_vdw_tip-ap_clust"

# molecules to be docked
molecules = [
        "../../pdb_files/3P5G/3P5G_r_u.pdb",
        "../../pdb_files/3P5G/3P5G_l_u.pdb",
] 


[topoaa] 

[rigidbody]
ambig_fname = "../../pdb_files/3P5G/3P5G_tip-ap.tbl"
sampling = 1000
w_vdw = 1.0 

[caprieval]
reference_fname = "../../pdb_files/3P5G/3P5G_analysis.pdb"

[rmsdmatrix]
resdic_A = [ 96 , 102 , 110 , 111 , 85 , 86 , 87 , 88 , 90 ] 
resdic_B = [ 1,  2,  3,    ] 

[clustrmsd]
criterion = 'maxclust'
n_clusters = 50 

[seletopclusts]
top_models = 5 

[caprieval]
reference_fname = "../../pdb_files/3P5G/3P5G_analysis.pdb"

[flexref]
ambig_fname = "../../pdb_files/3P5G/3P5G_tip-ap.tbl"
tolerance = 5 

[caprieval]
reference_fname = "../../pdb_files/3P5G/3P5G_analysis.pdb"

[rmsdmatrix]
resdic_A = [ 96 , 102 , 110 , 111 , 85 , 86 , 87 , 88 , 90 ] 
resdic_B = [ 1,  2,  3,    ] 

[clustrmsd]
criterion = 'distance'
linkage = 'average'
min_population = 4
clust_cutoff = 2.5 

[caprieval]
reference_fname = "../../pdb_files/3P5G/3P5G_analysis.pdb"

