# ===========================================================
#      Protein-glycan docking with HADDOCK3
#
#  This workflow will dock a bound glycan to a bound
#  protein, with the default haddock scoring function
#  and ti-aa restraints (true interface on both
#  protein and glycan).
# ===========================================================


#general section

mode = "mpi"
ncores = 16
run_dir = "run_bound_default_ti-aa"

# molecules to be docked
molecules = [
	"../../pdb_files/6N35/6N35_r_b.pdb",
	"../../pdb_files/6N35/6N35_l_b.pdb",
]

[topoaa] 

[rigidbody]
ambig_fname = "../../pdb_files/6N35/6N35_ti-aa.tbl"
sampling = 1000 

[caprieval]
reference_fname = "../../pdb_files/6N35/6N35_analysis.pdb"

[rmsdmatrix]
resdic_A = [ 317 , 242 , 243 , 244 , 310 , 311 , 316 , 315 , 92 , 93 , 318 , 319 ] 
resdic_B = [ 1 , 2 ] 


[clustrmsd]
criterion = 'distance'
linkage = 'average'
min_population = 4
clust_cutoff = 2.5 

[caprieval]
reference_fname = "../../pdb_files/6N35/6N35_analysis.pdb"

