# ===========================================================
#      Protein-glycan docking with HADDOCK3
#
#  This workflow will dock a bound glycan to a bound
#  protein, with the default haddock scoring function
#  and ti-aa restraints (true interface on both
#  protein and glycan).
# ===========================================================


#general section

mode = "mpi"
ncores = 16
run_dir = "run_bound_default_ti-aa"

# molecules to be docked
molecules = [
	"../../pdb_files/5AWQ/5AWQ_r_b.pdb",
	"../../pdb_files/5AWQ/5AWQ_l_b.pdb",
]

[topoaa] 

[rigidbody]
ambig_fname = "../../pdb_files/5AWQ/5AWQ_ti-aa.tbl"
sampling = 1000 

[caprieval]
reference_fname = "../../pdb_files/5AWQ/5AWQ_analysis.pdb"

[rmsdmatrix]
resdic_A = [ 67 , 68 , 69 , 70 , 71 , 197 , 199 , 110 , 146 , 274 , 254 , 250 , 187 , 188 , 30 ] 
resdic_B = [ 1 , 2 , 3 ] 


[clustrmsd]
criterion = 'distance'
linkage = 'average'
min_population = 4
clust_cutoff = 2.5 

[caprieval]
reference_fname = "../../pdb_files/5AWQ/5AWQ_analysis.pdb"

