# ===========================================================
#      Protein-glycan docking with HADDOCK3
#
#  This workflow will dock a bound glycan to a bound
#  protein, with the default haddock scoring function
#  and ti-aa restraints (true interface on both
#  protein and glycan).
# ===========================================================


#general section

mode = "mpi"
ncores = 16
run_dir = "run_bound_default_ti-aa"

# molecules to be docked
molecules = [
	"../../pdb_files/1QFO/1QFO_r_b.pdb",
	"../../pdb_files/1QFO/1QFO_l_b.pdb",
]

[topoaa] 

[rigidbody]
ambig_fname = "../../pdb_files/1QFO/1QFO_ti-aa.tbl"
sampling = 1000 

[caprieval]
reference_fname = "../../pdb_files/1QFO/1QFO_analysis.pdb"

[rmsdmatrix]
resdic_A = [ 96 , 2 , 101 , 103 , 104 , 105 , 43 , 107 ] 
resdic_B = [ 2 , 3 ] 


[clustrmsd]
criterion = 'distance'
linkage = 'average'
min_population = 4
clust_cutoff = 2.5 

[caprieval]
reference_fname = "../../pdb_files/1QFO/1QFO_analysis.pdb"

