# ===========================================================
#      Protein-glycan docking with HADDOCK3
#
#  This workflow will dock an unbound glycan (generated 
#  with GLYCAM) to an unbound protein, with van der 
#  Waals energy weight increased from 0.01 to 1.0 in 
#  the rigid body haddock scoring function and tip-ap 
#  restraints (true-interface-protein, glycan fully passive).
# ===========================================================

#general section

mode = "mpi"
ncores = 16
run_dir = "run_unbound_vdw_tip-ap_clust"

# molecules to be docked
molecules = [
        "../../pdb_files/1UXX/1UXX_r_u.pdb",
        "../../pdb_files/1UXX/1UXX_l_u.pdb",
] 


[topoaa] 

[rigidbody]
ambig_fname = "../../pdb_files/1UXX/1UXX_tip-ap.tbl"
sampling = 1000
w_vdw = 1.0 

[caprieval]
reference_fname = "../../pdb_files/1UXX/1UXX_analysis.pdb"

[rmsdmatrix]
resdic_A = [ 60 , 113 , 18 , 19 , 20 , 21 , 115 , 87 , 88 , 58 , 59 , 28 , 29 ] 
resdic_B = [ 1,  2,  3,  4,  5,    ] 

[clustrmsd]
criterion = 'maxclust'
n_clusters = 50 

[seletopclusts]
top_models = 5 

[caprieval]
reference_fname = "../../pdb_files/1UXX/1UXX_analysis.pdb"

[flexref]
ambig_fname = "../../pdb_files/1UXX/1UXX_tip-ap.tbl"
tolerance = 5 

[caprieval]
reference_fname = "../../pdb_files/1UXX/1UXX_analysis.pdb"

[rmsdmatrix]
resdic_A = [ 60 , 113 , 18 , 19 , 20 , 21 , 115 , 87 , 88 , 58 , 59 , 28 , 29 ] 
resdic_B = [ 1,  2,  3,  4,  5,    ] 

[clustrmsd]
criterion = 'distance'
linkage = 'average'
min_population = 4
clust_cutoff = 2.5 

[caprieval]
reference_fname = "../../pdb_files/1UXX/1UXX_analysis.pdb"

