# ===========================================================
#      Protein-glycan docking with HADDOCK3
#
#  This workflow will dock a bound glycan to a bound
#  protein, with van der Waals energy weight increased
#  from 0.01 to 1.0 in the rigid body haddock
#  scoring function and tip-ap restraints 
#  (true-interface-protein, glycan fully passive).
# ===========================================================

#general section

mode = "mpi"
ncores = 16
run_dir = "run_bound_vdw_tip-ap"

# molecules to be docked
molecules = [
	"../../pdb_files/3WH1/3WH1_r_b.pdb",
	"../../pdb_files/3WH1/3WH1_l_b.pdb",
]

[topoaa] 

[rigidbody]
ambig_fname = "../../pdb_files/3WH1/3WH1_tip-ap.tbl"
sampling = 1000 
w_vdw = 1.0

[caprieval]
reference_fname = "../../pdb_files/3WH1/3WH1_analysis.pdb"

[rmsdmatrix]
resdic_A = [ 137 , 161 , 162 , 165 , 166 , 174 , 178 , 181 , 182 , 59 , 60 , 62 , 66 , 68 , 69 , 70 , 97 , 98 , 99 , 100 , 101 , 104 ] 
resdic_B = [ 1,  2,  3,  4,    ] 


[clustrmsd]
criterion = 'distance'
linkage = 'average'
min_population = 4
clust_cutoff = 2.5 

[caprieval]
reference_fname = "../../pdb_files/3WH1/3WH1_analysis.pdb"

