# ===========================================================
#      Protein-glycan docking with HADDOCK3
#
#  This workflow will dock a bound glycan to a bound
#  protein, with van der Waals energy weight increased
#  from 0.01 to 1.0 in the rigid body haddock
#  scoring function and tip-ap restraints 
#  (true-interface-protein, glycan fully passive).
# ===========================================================

#general section

mode = "mpi"
ncores = 16
run_dir = "run_bound_vdw_tip-ap"

# molecules to be docked
molecules = [
	"../../pdb_files/6UG7/6UG7_r_b.pdb",
	"../../pdb_files/6UG7/6UG7_l_b.pdb",
]

[topoaa] 

[rigidbody]
ambig_fname = "../../pdb_files/6UG7/6UG7_tip-ap.tbl"
sampling = 1000 
w_vdw = 1.0

[caprieval]
reference_fname = "../../pdb_files/6UG7/6UG7_analysis.pdb"

[rmsdmatrix]
resdic_A = [ 33 , 263 , 264 , 265 , 267 , 49 , 242 , 243 , 244 , 309 , 312 , 313 , 90 , 91 , 93 , 95 , 31 ] 
resdic_B = [ 1,  2,  3,  4,  5,  6 ] 


[clustrmsd]
criterion = 'distance'
linkage = 'average'
min_population = 4
clust_cutoff = 2.5 

[caprieval]
reference_fname = "../../pdb_files/6UG7/6UG7_analysis.pdb"

