# ===========================================================
#      Protein-glycan docking with HADDOCK3
#
#  This workflow will dock a bound glycan to a bound
#  protein, with the default haddock scoring function
#  and ti-aa restraints (true interface on both
#  protein and glycan).
# ===========================================================


#general section

mode = "mpi"
ncores = 16
run_dir = "run_bound_default_ti-aa"

# molecules to be docked
molecules = [
	"../../pdb_files/3AOF/3AOF_r_b.pdb",
	"../../pdb_files/3AOF/3AOF_l_b.pdb",
]

[topoaa] 

[rigidbody]
ambig_fname = "../../pdb_files/3AOF/3AOF_ti-aa.tbl"
sampling = 1000 

[caprieval]
reference_fname = "../../pdb_files/3AOF/3AOF_analysis.pdb"

[rmsdmatrix]
resdic_A = [ 96 , 515 , 325 , 104 , 558 , 335 , 400 , 401 , 591 , 597 , 503 , 59 , 510 ] 
resdic_B = [ 1 , 2 , 3 ] 


[clustrmsd]
criterion = 'distance'
linkage = 'average'
min_population = 4
clust_cutoff = 2.5 

[caprieval]
reference_fname = "../../pdb_files/3AOF/3AOF_analysis.pdb"

