# ===========================================================
#      Protein-glycan docking with HADDOCK3
#
#  This workflow will dock a bound glycan to a bound
#  protein, with van der Waals energy weight increased
#  from 0.01 to 1.0 in the rigid body haddock
#  scoring function and tip-ap restraints 
#  (true-interface-protein, glycan fully passive).
# ===========================================================

#general section

mode = "mpi"
ncores = 16
run_dir = "run_bound_vdw_tip-ap"

# molecules to be docked
molecules = [
	"../../pdb_files/3G83/3G83_r_b.pdb",
	"../../pdb_files/3G83/3G83_l_b.pdb",
]

[topoaa] 

[rigidbody]
ambig_fname = "../../pdb_files/3G83/3G83_tip-ap.tbl"
sampling = 1000 
w_vdw = 1.0

[caprieval]
reference_fname = "../../pdb_files/3G83/3G83_analysis.pdb"

[rmsdmatrix]
resdic_A = [ 137 , 138 , 139 , 117 , 119 , 121 , 125 ] 
resdic_B = [ 1,  2,    ] 


[clustrmsd]
criterion = 'distance'
linkage = 'average'
min_population = 4
clust_cutoff = 2.5 

[caprieval]
reference_fname = "../../pdb_files/3G83/3G83_analysis.pdb"

